import "../scss/styles.scss";
import * as bootstrap from "bootstrap";
import "./draggableobjects.js";
import "./localstoragecheck.js";
import "./mannekeclickcheck.js";
import "./offeringCheck.js";
import "./wordcheck.js";
import "./navanimate.js";
import "./shootingrange.js";
import "./music.js";
// import "./admin.js";
